config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :employee_details
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'employee_details#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee_detail.rb
class EmployeeDetail < ApplicationRecord
    validates :fName, :lName, :email, presence: true
    validates :fName, length: { minimum: 3 }
    validates :experience, numericality: true
    validates :email, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    def set_current_user
      # finds user with session data and stores it if present
      Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
    end
    def require_user_logged_in!
      # allows only logged in user
      redirect_to sign_in_path, alert: 'You must be signed in' if Current.user.nil?
    end
end

app/controllers/employee_details_controller.rb
class EmployeeDetailsController < ApplicationController
  before_action :set_employee_detail, only: %i[ show edit update destroy ]

  # GET /employee_details or /employee_details.json
  def index
    @employee_details = EmployeeDetail.all
  end

  # GET /employee_details/1 or /employee_details/1.json
  def show
  end

  # GET /employee_details/new
  def new
    @employee_detail = EmployeeDetail.new
  end

  # GET /employee_details/1/edit
  def edit
  end

  # POST /employee_details or /employee_details.json
  def create
    @employee_detail = EmployeeDetail.new(employee_detail_params)

    
    respond_to do |format|
      if @employee_detail.save
        
        AlertAdminMailer.alert_admin(@employee_detail).deliver

        format.html { redirect_to @employee_detail, notice: "Employee detail was successfully created." }
        format.json { render :show, status: :created, location: @employee_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_details/1 or /employee_details/1.json
  def update
    respond_to do |format|
      if @employee_detail.update(employee_detail_params)
        format.html { redirect_to @employee_detail, notice: "Employee detail was successfully updated." }
        format.json { render :show, status: :ok, location: @employee_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_details/1 or /employee_details/1.json
  def destroy
    @employee_detail.destroy
    respond_to do |format|
      format.html { redirect_to employee_details_url, notice: "Employee detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_detail
      @employee_detail = EmployeeDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_detail_params
      params.require(:employee_detail).permit(:fName, :lName, :email, :role, :experience)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_details_helper.rb
module EmployeeDetailsHelper
end

app/views/employee_details/_form.html.erb
<%= form_with(model: employee_detail, local: true) do |form| %>
  <% if employee_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee_detail.errors.count, "error") %> prohibited this employee_detail from being saved:</h2>

      <ul>
      <% employee_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "First Name:" %>
    <%= form.text_field :fName %>
  </div>

  <div class="field">
    <%= form.label "Last Name:" %>
    <%= form.text_field :lName %>
  </div>

  <div class="field">
    <%= form.label "Email ID:" %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label "Role:" %>
    <%= form.text_field :role %>
  </div>

  <div class="field">
    <%= form.label "Years of Experience:" %>
    <%= form.number_field :experience %>
  </div>

  <div class="actions">
    <%= form.submit "Add Employee" %>
  </div>
<% end %>

app/views/employee_details/edit.html.erb
<h1>Editing Employee Detail</h1>

<%= render 'form', employee_detail: @employee_detail %>

<%= link_to 'Show', @employee_detail %> |
<%= link_to 'Back', employee_details_path %>

app/views/employee_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employee Details</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Role</th>
      <th>Experience</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee_details.each do |employee_detail| %>
      <tr>
        <td><%= employee_detail.fName %></td>
        <td><%= employee_detail.lName %></td>
        <td><%= employee_detail.email %></td>
        <td><%= employee_detail.role %></td>
        <td><%= employee_detail.experience %></td>
        <td><%= link_to 'Show', employee_detail %></td>
        <td><%= link_to 'Edit', edit_employee_detail_path(employee_detail) %></td>
        <td><%= link_to 'Destroy', employee_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Employee', new_employee_detail_path %>

app/views/employee_details/new.html.erb
<h1>New Employee Detail</h1>

<%= render 'form', employee_detail: @employee_detail %>

<%= link_to 'Back', employee_details_path %>

app/views/employee_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @employee_detail.fName %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @employee_detail.lName %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee_detail.email %>
</p>

<p>
  <strong>Role:</strong>
  <%= @employee_detail.role %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @employee_detail.experience %>
</p>

<%= link_to 'Edit', edit_employee_detail_path(@employee_detail) %> |
<%= link_to 'Back', employee_details_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employees</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>